version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: golang
      POSTGRES_PASSWORD: golang
      POSTGRES_DB: golang
    ports:
      - "6942:5432"
    volumes:
      - golang_rest_api_database:/var/lib/postgresql/data

volumes:
  golang_rest_api_database: